version: '3.8'

services:
#  ms-order-api:
#    image: ms-order-api:latest
#    container_name: ms-order-api
#    ports:
#      - "8080:8080"
#    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    network_mode: "host"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    ports:
      - "4317:4317" # OTLP gRPC
      - "3200:3200" # Tempo HTTP
    volumes:
      - ./tempo.yml:/etc/tempo.yml

volumes:
  grafana-storage: