apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-order-api
  namespace: ms-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-order-api
  template:
    metadata:
      labels:
        app: ms-order-api
    spec:
      containers:
        - name: ms-order-api
          image: ms-order-api:0.0.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
