apiVersion: v1
kind: Service
metadata:
  name: ms-order-api
  namespace: ms-order
spec:
  selector:
    app: ms-order-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
